version: '3.8'

services:
  backend:
    build: ./backend
    container_name: geekgift-backend
    volumes:
      - geekgift_data:/app/db
      - geekgift_uploads:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: geekgift-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  geekgift_data:
  geekgift_uploads:
